//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiCuAstaPasta.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RestaurantMVPEntities : DbContext
    {
        public RestaurantMVPEntities()
            : base("name=RestaurantMVPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alergeni> Alergenis { get; set; }
        public virtual DbSet<Categorie> Categories { get; set; }
        public virtual DbSet<Comanda> Comandas { get; set; }
        public virtual DbSet<ComandaMeniu> ComandaMenius { get; set; }
        public virtual DbSet<ComandaPreparat> ComandaPreparats { get; set; }
        public virtual DbSet<Meniu> Menius { get; set; }
        public virtual DbSet<MeniuPreparat> MeniuPreparats { get; set; }
        public virtual DbSet<Preparat> Preparats { get; set; }
        public virtual DbSet<PreparatAlergeni> PreparatAlergenis { get; set; }
        public virtual DbSet<Utilizator> Utilizators { get; set; }
    
        public virtual ObjectResult<spAutentificareUtilizator_Result> spAutentificareUtilizator(string email, string parola)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var parolaParameter = parola != null ?
                new ObjectParameter("Parola", parola) :
                new ObjectParameter("Parola", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAutentificareUtilizator_Result>("spAutentificareUtilizator", emailParameter, parolaParameter);
        }
    
        public virtual int spInregistrareUtilizator(string prenume, string nume, string email, string parola, string telefon, string adresa)
        {
            var prenumeParameter = prenume != null ?
                new ObjectParameter("Prenume", prenume) :
                new ObjectParameter("Prenume", typeof(string));
    
            var numeParameter = nume != null ?
                new ObjectParameter("Nume", nume) :
                new ObjectParameter("Nume", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var parolaParameter = parola != null ?
                new ObjectParameter("Parola", parola) :
                new ObjectParameter("Parola", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var adresaParameter = adresa != null ?
                new ObjectParameter("Adresa", adresa) :
                new ObjectParameter("Adresa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInregistrareUtilizator", prenumeParameter, numeParameter, emailParameter, parolaParameter, telefonParameter, adresaParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> spReturneazaCostTotalMeniu(Nullable<int> iDMeniu)
        {
            var iDMeniuParameter = iDMeniu.HasValue ?
                new ObjectParameter("IDMeniu", iDMeniu) :
                new ObjectParameter("IDMeniu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("spReturneazaCostTotalMeniu", iDMeniuParameter);
        }
    
        public virtual ObjectResult<spReturneazaPreparateleMeniului_Result> spReturneazaPreparateleMeniului(Nullable<int> iDMeniu)
        {
            var iDMeniuParameter = iDMeniu.HasValue ?
                new ObjectParameter("IDMeniu", iDMeniu) :
                new ObjectParameter("IDMeniu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spReturneazaPreparateleMeniului_Result>("spReturneazaPreparateleMeniului", iDMeniuParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> spReturneazaStocMaximMeniu(Nullable<int> iDMeniu)
        {
            var iDMeniuParameter = iDMeniu.HasValue ?
                new ObjectParameter("IDMeniu", iDMeniu) :
                new ObjectParameter("IDMeniu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("spReturneazaStocMaximMeniu", iDMeniuParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> spReturneazaStocMaximPreparat(Nullable<int> iDPreparat)
        {
            var iDPreparatParameter = iDPreparat.HasValue ?
                new ObjectParameter("IDPreparat", iDPreparat) :
                new ObjectParameter("IDPreparat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("spReturneazaStocMaximPreparat", iDPreparatParameter);
        }
    }
}
